# Suppress warnings for missing classes that are not available on Android
# (generated by R8 - see missing_rules.txt)

-dontwarn javax.script.AbstractScriptEngine
-dontwarn javax.script.Compilable
-dontwarn javax.script.ScriptEngine
-dontwarn javax.script.ScriptEngineFactory

# Internal Telegram classes referenced by MVEL/other libs
-dontwarn org.telegram.messenger.AndroidUtilities
-dontwarn org.telegram.messenger.FileLog
-dontwarn org.telegram.messenger.LocaleController
-dontwarn org.telegram.messenger.MessagesController
-dontwarn org.telegram.messenger.NotificationCenter$NotificationCenterDelegate
-dontwarn org.telegram.messenger.NotificationCenter
-dontwarn org.telegram.messenger.NotificationsController
-dontwarn org.telegram.messenger.UserConfig
-dontwarn org.telegram.tgnet.InputSerializedData
-dontwarn org.telegram.tgnet.OutputSerializedData
-dontwarn org.telegram.tgnet.RequestDelegate
-dontwarn org.telegram.tgnet.SerializedData
-dontwarn org.telegram.tgnet.TLObject

-keep class dev.exterahook.** { *; }
-keep class com.exteragram.** { *; }
-keep class de.robv.android.xposed.** { *; }
-keep class org.telegram.** { *; }
-keepclassmembers class * {
    native <methods>;
}

# Coroutines & MainDispatcher service loader
-keep class kotlinx.coroutines.** { *; }
-keep class kotlinx.coroutines.android.** { *; }
-keep class kotlinx.coroutines.internal.** { *; }
-keep class kotlinx.coroutines.internal.MainDispatcherFactory { *; }
-keep class kotlinx.coroutines.android.AndroidDispatcherFactory { *; }
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory
-keepnames class kotlinx.coroutines.android.AndroidDispatcherFactory

